load("@rules_python//python:defs.bzl", "extract_wheel")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "backports.functools_lru_cache",
    srcs = ["@examples_checked_in_requirements_bzl__backports_functools_lru_cache_1_5_wheel//:wheel"],
)
