load("@rules_python//python:python.bzl", "extract_wheel")
load("@examples_checked_in_requirements_bzl//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "backports.functools_lru_cache",
    srcs = ["@examples_checked_in_requirements_bzl__backports_functools_lru_cache_1_5_wheel//:wheel"],
)
