load("@rules_python//python:defs.bzl", "extract_wheel")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "pip",
    srcs = ["@examples_checked_in_requirements_bzl__pip_9_0_0_wheel//:wheel"],
)
