# Image built from tools/Dockerfile
image: 'gitlab-master.nvidia.com:5005/ai-infra/rules_python:v2'

stages:
  - build
  - publish

build:
  tags:
    - acme-docker-reqfresh
  stage: build
  script: bazel test -- //... -//docs/...

publish:
  tags:
    - acme-docker-reqfresh
  stage: publish
  script:
    - export GIT_COMMIT_HASH=$(git rev-parse HEAD)
    - export KEY=ai-infra/rules_python/$GIT_COMMIT_HASH.tar.gz
    - git archive --prefix=rules_python-$GIT_COMMIT_HASH/ HEAD --format=tar.gz --output=$GIT_COMMIT_HASH.tar.gz
    - curl -I https://archives.nvda.ai/$KEY --fail && { echo "Must not overwrite existing files!"; exit 0; }
    - aws s3 cp $GIT_COMMIT_HASH.tar.gz s3://archives-nvda-ai/$KEY

