load("@rules_python//python:defs.bzl", "extract_wheel")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "wrapt",
    srcs = ["@examples_checked_in_requirements_bzl__wrapt_1_11_1_wheel//:wheel"],
)
