load("@rules_python//python:defs.bzl", "extract_wheel")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "decorator",
    srcs = ["@examples_checked_in_requirements_bzl__decorator_4_4_2_wheel//:wheel"],
)
