load("@rules_python//python:defs.bzl", "extract_wheel")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "numpy",
    srcs = ["@examples_checked_in_requirements_bzl__numpy_1_16_6_wheel//:wheel"],
)
