workspace(name = "example")

# PIP => bazel transition
local_repository(
    name = "rules_python",
    path = "../../.."
)

load("@rules_python//python:pip.bzl", "pip_repositories", "pip_import")
pip_repositories()

pip_import(
    name="pip_deps",
    requirements="//:requirements.txt",
)
load("@pip_deps//:requirements.bzl", "pip_install")
pip_install()
