load("@rules_python//python:defs.bzl", "extract_wheel")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "sqlalchemy",
    srcs = ["@examples_checked_in_requirements_bzl__SQLAlchemy_1_1_15_wheel//:wheel"],
)
