load("@rules_python//python:defs.bzl", "extract_wheel")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "six",
    srcs = ["@examples_checked_in_requirements_bzl__six_1_15_0_wheel//:wheel"],
)
