load("@rules_python//python:defs.bzl", "extract_wheel")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "backports.ssl_match_hostname",
    srcs = ["@examples_checked_in_requirements_bzl__backports_ssl_match_hostname_3_5_0_1_wheel//:wheel"],
)
