load("@rules_python//python:defs.bzl", "extract_wheel")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "pytz",
    srcs = ["@examples_checked_in_requirements_bzl__pytz_2020_1_wheel//:wheel"],
)
