load("@rules_python//python:defs.bzl", "extract_wheel")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "enum34",
    srcs = ["@examples_checked_in_requirements_bzl__enum34_1_1_10_wheel//:wheel"],
)
