load("@rules_python//python:defs.bzl", "extract_wheel")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "future",
    srcs = ["@examples_checked_in_requirements_bzl__future_0_18_2_wheel//:wheel"],
)
