load("@rules_python//python:python.bzl", "extract_wheel")
load("@examples_checked_in_requirements_bzl//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

extract_wheel(
    name = "future",
    srcs = ["@examples_checked_in_requirements_bzl__future_0_18_2_wheel//:wheel"],
)
